// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CinemaRoma.Models
{
    public class CinemaConfiguration : IEntityTypeConfiguration<Cinema>
    {
        public void Configure(EntityTypeBuilder<Cinema> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("Cinema_pk")
                .IsClustered(false);

            entity.ToTable("Cinema");

            entity.HasIndex(e => e.Id)
                .HasName("Cinema_Id_uindex")
                .IsUnique();

            entity.Property(e => e.Address).IsRequired();

            entity.Property(e => e.Location).IsRequired();
        }
    }
}
