// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CinemaRoma.Models
{
    public class DirectorConfiguration : IEntityTypeConfiguration<Director>
    {
        public void Configure(EntityTypeBuilder<Director> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("Director_pk")
                .IsClustered(false);

            entity.ToTable("Director");

            entity.HasIndex(e => e.Id)
                .HasName("Director_Id_uindex")
                .IsUnique();

            entity.Property(e => e.DateBirth).HasColumnType("date");

            entity.Property(e => e.FirstName).IsRequired();

            entity.Property(e => e.LastName).IsRequired();

            entity.Property(e => e.MiddleName).IsRequired();
        }
    }
}
