// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CinemaRoma.Models
{
    public class GenreConfiguration : IEntityTypeConfiguration<Genre>
    {
        public void Configure(EntityTypeBuilder<Genre> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("Genres_pk")
                .IsClustered(false);

            entity.HasIndex(e => e.Id)
                .HasName("Genres_Id_uindex")
                .IsUnique();
        }
    }
}
