// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CinemaRoma.Models
{
    public class MovieConfiguration : IEntityTypeConfiguration<Movie>
    {
        public void Configure(EntityTypeBuilder<Movie> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("Movie_pk")
                .IsClustered(false);

            entity.ToTable("Movie");

            entity.HasIndex(e => e.Id)
                .HasName("Movie_Id_uindex")
                .IsUnique();

            entity.Property(e => e.Description).IsRequired();

            entity.Property(e => e.RentelDate)
                .HasColumnType("date")
                .HasComment("Дата выпуска	");

            entity.Property(e => e.Title).IsRequired();

            entity.HasOne(d => d.Genre)
                .WithMany(p => p.Movies)
                .HasForeignKey(d => d.GenreId)
                .HasConstraintName("Movie_Genres_Id_fk");

            entity.HasOne(d => d.Producer)
                .WithMany(p => p.Movies)
                .HasForeignKey(d => d.ProducerId)
                .HasConstraintName("Movie_Director_Id_fk");
        }
    }
}
