// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


using CinemaRoma.Properties;

namespace CinemaRoma.Models
{
    public partial class Actor
    {
        public Actor()
        {
            MovieActors = new HashSet<MovieActor>();
        }

        public int Id { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "ActorFirstName")]
        [Required]
        [MinLength(2, ErrorMessage = "Неверный формат имени шаблона")]
        [MaxLength(20/*, ErrorMessage = "Неверный формат имени шаблона"*/)]
        public string FirstName { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "ActorMiddleName")]
        [Required]
        [MinLength(2, ErrorMessage = "Неверный формат имени шаблона")]
        [MaxLength(20, ErrorMessage = "Неверный формат имени шаблона")]
        public string MiddleName { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "ActorLastName")]
        [MinLength(2, ErrorMessage = "Неверный формат имени шаблона")]
        [Required]
        [MaxLength(20, ErrorMessage = "Неверный формат имени шаблона")]
        public string LastName { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "DateBirth")]
        [DataType(DataType.DateTime)]
        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateBirth { get; set; }

        public virtual ICollection<MovieActor> MovieActors { get; set; }



        [Display(ResourceType = typeof(Resources), Name = "ActorFullName")]
        [NotMapped]
        public string FullName => $"{MiddleName} {FirstName?[0]}.{LastName?[0]}.";


        public override string ToString() => $"{FullName}";

    }
}
