// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


using CinemaRoma.Properties;

namespace CinemaRoma.Models
{
    public partial class Actor
    {
        public Actor()
        {
            MovieActors = new HashSet<MovieActor>();
        }

        public int Id { get; set; }

        [Display(ResourceType = typeof(Resources) , Name = "ActorFirstName")]
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }

        public DateTime DateBirth { get; set; }

        public virtual ICollection<MovieActor> MovieActors { get; set; }

        [NotMapped]
        [Display(ResourceType = typeof(Resources) , Name = "ActorFullName")]
        public string FullName { get; set; }

    }
}