// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


using CinemaRoma.Properties;

namespace CinemaRoma.Models
{
    public partial class Actor
    {
        public Actor()
        {
            MovieActors = new HashSet<MovieActor>();
        }

        public int Id { get; set; }

        [Display(ResourceType = typeof(Resources) , Name = "ActorFirstName")]
        public string FirstName { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "ActorMiddleName")]
        public string MiddleName { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "ActorLastName")]
        public string LastName { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "DateBirth")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true,DataFormatString = "{0:dd'.'MM'.'yyyy}")]
        public DateTime DateBirth { get; set; }

        public virtual ICollection<MovieActor> MovieActors { get; set; }



        [Display(ResourceType = typeof(Resources), Name = "ActorFullName")]
        [NotMapped]
        public string FullName => $"{MiddleName} {FirstName[0]}.{LastName[0]}.";


        public override string ToString() => $"{FullName}";

    }
}
