// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CinemaRoma.Properties;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CinemaRoma.Models
{
    public partial class CinemaMovie
    {
        [Display(ResourceType = typeof(Resources), Name = "Title")]
        public int MovieId { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "Location")]
        public int CinemaId { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "DateStartRental")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateStartRental { get; set; }


        [Display(ResourceType = typeof(Resources), Name = "DateEndRental")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateEndRental { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Cinema")]
        public virtual Cinema Cinema { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Movie")]
        public virtual Movie Movie { get; set; }
    }
}
