// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CinemaRoma.Models
{
    public partial class Cinema
    {
        public Cinema()
        {
            CinemaMovies = new HashSet<CinemaMovie>();
        }

        public int Id { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }

        public virtual ICollection<CinemaMovie> CinemaMovies { get; set; }
    }
}