// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CinemaRoma.Properties;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CinemaRoma.Models
{
    public partial class Director
    {
        public Director()
        {
            Movies = new HashSet<Movie>();
        }

        public int Id { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "ActorFirstName")]
        public string FirstName { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "ActorMiddleName")]
        public string MiddleName { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "ActorLastName")]
        public string LastName { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "DateEndRental")]
        public DateTime DateBirth { get; set; }

        public virtual ICollection<Movie> Movies { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "ActorFullName")]
        [NotMapped]
        public string FullName => $"{MiddleName} {FirstName[0]}.{LastName[0]}.";


        public override string ToString() => $"{FullName}";
    }
}