// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CinemaRoma.Models
{
    public partial class Movie
    {
        public Movie()
        {
            CinemaMovies = new HashSet<CinemaMovie>();
            MovieActors = new HashSet<MovieActor>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public DateTime RentelDate { get; set; }
        public int ProducerId { get; set; }
        public int GenreId { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual Director Producer { get; set; }
        public virtual ICollection<CinemaMovie> CinemaMovies { get; set; }
        public virtual ICollection<MovieActor> MovieActors { get; set; }
    }
}