// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CinemaRoma.Properties;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CinemaRoma.Models
{
    public partial class Movie
    {
        public Movie()
        {
            CinemaMovie = new HashSet<CinemaMovie>();
            MovieActor = new HashSet<MovieActor>();
        }

        public int Id { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "Title")]
        [DataType(DataType.Text)]
        [MinLength(5)]
        [Required]
        public string Title { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Description")]
        [MinLength(3)]
        [Required]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Duration")]
        [Required]
        public int Duration { get; set; }



        [Display(ResourceType = typeof(Resources), Name = "Year_of_issue")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true,DataFormatString = "{0:dd'.'MM'.'yyyy}")]
        [Required]
        public DateTime RentelDate { get; set; }
        
        [Display(ResourceType = typeof(Resources), Name = "Producer")]

        public int ProducerId { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "GenreName")]
        public int GenreId { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "GenreName")]

        public virtual Genre Genre { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Producer")]

        public virtual Director Producer { get; set; }

        public virtual ICollection<CinemaMovie> CinemaMovie { get; set; }
        public virtual ICollection<MovieActor> MovieActor { get; set; }

        public override string ToString()
        {
            return $"{Title}";
        }
    }
}
