// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CinemaRoma.Properties;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CinemaRoma.Models
{
    public partial class MovieActor
    {
        public int MovieId { get; set; }
        public int ActorId { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Actor")]
        public virtual Actor Actor { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "Movie")]
        public virtual Movie Movie { get; set; }
    }
}