// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CinemaRoma.Properties;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CinemaRoma.Models
{
    public partial class Movie
    {
        public Movie()
        {
            CinemaMovies = new HashSet<CinemaMovie>();
            MovieActors = new HashSet<MovieActor>();
        }

        public int Id { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "Title")]
        public string Title { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "Description")] 
        public string Description { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "Duration")]
        public int Duration { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "DateStartRental")]
        public DateTime RentelDate { get; set; }
        public int ProducerId { get; set; }
        public int GenreId { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "GenreName")]
        public virtual Genre Genre { get; set; }
        [Display(ResourceType = typeof(Resources), Name = "Producer")]
        public virtual Director Producer { get; set; }
        public virtual ICollection<CinemaMovie> CinemaMovies { get; set; }
        public virtual ICollection<MovieActor> MovieActors { get; set; }

        public override string ToString()
        {
            return $"{Title}";


        }
    }
}